# Generated by Django 5.0.6 on 2024-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_address_order_card_number_order_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
